### ISSUE TITLE
Accessing has many on user

### ISSUE THREAD

**Issue by duncanmcclean** [duncanmcclean/runway#196]
### Discussed in https://github.com/duncanmcclean/runway/discussions/195

<div type='discussions-op-text'>

<sup>Originally posted by **Keoghan** January 18, 2023</sup>
Hi, 

Thanks for this package, it's a super addition to the world of Statamic.

I'm having trouble accessing a HasMany relationship on a user record. 

The relations are all in the DB, and I have the relationship set up in the \App\Models\User. I suspect the issue is that the instance of the User in the control panel is not an \App\Models\User but something else?

Any thoughts on how to work with it?

Thanks, Keoghan</div>

**Comment by Keoghan** [comment]
Not sure where to put this additional information:

The user is coming through as `Statamic\Auth\Eloquent\User`. As standard this doesn't include any relationships from the usual `App\Models\User`.

I can begin to pass the relationships through using computed - in this case jobs.

```php
User::computed('jobs', function ($user, $value) {
     return $user->model()->jobs;
});
```

However, when the related models appear in the table, the first column is a json representation of the whole model, and the remaining columns are empty.

**Comment by duncanmcclean** [comment]
It might be worth checking if you can do updates?

**Comment by Keoghan** [comment]
I am having some issues with updates - will attempt to summarise tomorrow.

**Comment by duncanmcclean** [comment]
Yeah, I'll take a look when I have some free time.

My suspicion is that you won't be able to manage "real" HasMany relationships without making the User a resource on Runway.

**Comment by Keoghan** [comment]
Hi Duncan, 

Thanks - I have been playing with adjusting settings etc and I can get the `jobs` table to behave nicely on its own. When it is drawn in through the mechanism above, the data is not processing the same way (so belongs to relations on jobs show as integers, dates are not formatted etc) - and updates fail for the moment. 

I will create an alternative model to test through with it as a Resource on Runway - doing so with User didn't change the outcome so far.

**Comment by Keoghan** [comment]
Thanks Duncan. I see what you are saying but I am slightly confused by it.

Loosely here we have: 

- User, a Statamic Eloquent model. 
- Department, a Runway Model, ID, name
- Job, a Runway model with belongsTo relations to User and Department.

The user has a hasMany relation with Jobs. 

In this situation, all the data is stored in the Runway tables - so I don't see why we would need to be trying to save id's only. We can access full eloquent models for each job from the user using the computed jobs property, for example.

The table could be populated with a separate call Ajax outside of the main script - using user_id as a filter variable. As the straight Jobs Runway listing works well.

Perhaps I have missed something? I did try setting up a Runway model for users but since I am trying to extend the norma l user edit form, it is still passed the Statamic Auth User model.

**Comment by duncanmcclean** [comment]
You won't be able to use the Has Many fieldtype with native Eloquent relationships when using the normal users edit form, even though you're using Eloquent for your users. 

You will need to setup a separate Runway resource for users if you want to use the native Eloquent relationships, that's just the way the fieldtype works.

If you need to manage the Eloquent relationships using the normal users edit form, I'd suggest looking into creating your own fieldtype to handle it.

**Comment by Keoghan** [comment]
Ok, thanks for your assistance 👍

**Comment by Boefjim** [comment]
Not sure where to ask this, but I've ran into the same issue where a relationship on the user form would not function correctly. Since it also causes some computed fields to not work correctly, I decided to create a normal runway resource for the users in order to fix that.

While the relationship and computed field now function perfectly, it has caused a new issue.
The roles & groups fields no longer function correctly, it seems Runway does not support the `user_roles` & `user_groups` field types?
I don´t see it listed in the list of supported fieldtypes: https://runway.duncanmcclean.com/blueprints#content-supported-fieldtypes

Would it be possible to add support for these fields?

**Comment by duncanmcclean** [comment]
This issue is over a year old. To avoid past participants being notified, are you able to open a new issue instead? Feel free to reference this one.

Runway should support any fieldtype, you just need to make sure the column type is right (eg. if it has "max items" = 1, it should be a string, otherwise, it should be a `json` column). If any fieldtypes are missing from the docs, feel free to submit a PR to update the docs.
