### ISSUE TITLE
Using a model more than once is not possible

### ISSUE THREAD

**Issue by royduin** [duncanmcclean/runway#256]
### Description

Because the key of the array in the configuration is the model. Maybe switch to just an ordered array with the model as option within?

### Steps to reproduce

Create a resource with the same model, reference with an example: https://github.com/duncanmcclean/runway/pull/255

### Environment

Does not apply

**Comment by royduin** [comment]
Things like this will become a problem: https://github.com/duncanmcclean/runway/search?q=findResourceByModel

**Comment by duncanmcclean** [comment]
Why would you be creating more than 1 resource with the same model?

**Comment by royduin** [comment]
Good question! Let's say I've a product model with an attribute model. Within the attributes model all attributes are stored like color, brand, etc. Now I'd like to have an resource in Statamic with just the brands and another one with just the colors.

**Comment by duncanmcclean** [comment]
Ah, okay! 

As you can tell, Runway's only been built to allow for a model to be assigned to a single resource. In order to change this, it would require quite a bit of work (as in some places we need to get a resource from a `Model` instance which obviously we wouldn't be able to do if the relationship between a model & a resource wasn't 1-1).

For now, we're not going to make it possible for a model to be used to create more than one resource. 

However, you could workaround this by creating a model for each of the types of attributes and apply a global scope to each of the models so you only get colours returned from the `Colour` model.

I know it's not ideal but unfortunately I don't have enough bandwidth to change this right now & I don't think it's something a lot of people will (& at least haven't in the past) run into. I hope that makes sense!

**Comment by royduin** [comment]
No problem, thank you for your answer!
